create DATABASE DBTIENDA_SMART_DB
go

use DBTIENDA_SMART_DB
go

CREATE TABLE TBL_CLIENTES (
	NID_CLIENTE INT IDENTITY (1,1) PRIMARY KEY,
	CNOMBRE NVARCHAR(50) NOT NULL,
	CPRIMER_APELLIDO NVARCHAR(50) NOT NULL,
	CSEGUNDO_APELLIDO NVARCHAR (50),
	CDIRECCION NVARCHAR(150) NOT NULL
	)


CREATE TABLE TBL_USUARIOS(
	NID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	CUSUARIO NVARCHAR(100) NOT NULL UNIQUE,
	CPASSWORD_HASH NVARCHAR(200) NOT NULL,
	CROL NVARCHAR(20) NOT NULL,
	NID_CLIENTE INT NULL,
	CONSTRAINT FK_USUARIO_CLIENTE FOREIGN KEY (NID_CLIENTE) 
	REFERENCES TBL_CLIENTES (NID_CLIENTE))


CREATE TABLE TBL_SUCURSALES (
	NID_SUCURSAL INT IDENTITY(1,1) PRIMARY KEY,
	CNOMBRE_SUCURSAL NVARCHAR(100) NOT NULL,
	CDIRECCION_SUCURSAL NVARCHAR(100) NOT NULL,
	BHABILITADO BIT NOT NULL)

 CREATE TABLE TBL_ARTICULOS (
	NID_ARTICULO INT IDENTITY(1,1) PRIMARY KEY,
	CNOMBRE_ARTICULO NVARCHAR (100) NOT NULL,
	CCODIGO NVARCHAR(100) NOT NULL,
	CDESCRIPCION NVARCHAR(300) NOT NULL,
	DPRECIO DECIMAL(18,2) NOT NULL,
	CIMAGEN NVARCHAR(max) NOT NULL,
	BHABILITADO BIT NOT NULL
	)

CREATE TABLE TBL_SUCURSALES_ARTICULOS (
	NID_SUCURSAL_ARTICULO INT IDENTITY(1,1) PRIMARY KEY,
	NID_SUCURSAL INT NOT NULL,
	NID_ARTICULO INT NOT NULL,
	NSTOCK INT NOT NULL,
	DFECHA_ADQUIRIDO DATETIME,
	CONSTRAINT FK_SUCURSAL FOREIGN KEY (NID_SUCURSAL) 
	REFERENCES TBL_SUCURSALES (NID_SUCURSAL),
	CONSTRAINT FK_ARTICULO_SUCURSALES FOREIGN KEY (NID_ARTICULO) 
	REFERENCES TBL_ARTICULOS (NID_ARTICULO))

CREATE TABLE TBL_CARRITO (
    NID_CARRITO INT IDENTITY(1,1) PRIMARY KEY,
    NID_USUARIO INT NOT NULL,
    DFECHA_CREACION DATETIME NOT NULl,
    BHABILITADO BIT NOT NULL,
    CONSTRAINT FK_CARRITO_USUARIO FOREIGN KEY (NID_USUARIO)
    REFERENCES TBL_USUARIOS(NID_USUARIO))

CREATE TABLE TBL_CARRITO_ARTICULOS (
    NID_CARRITO_ARTICULO INT IDENTITY(1,1) PRIMARY KEY,
    NID_CARRITO INT NOT NULL,
    NID_ARTICULO INT NOT NULL,
    NCANTIDAD INT NOT NULL,
    DPRECIO DECIMAL(18,2) NOT NULL,
    BHABILITADO BIT NOT NULL,
    CONSTRAINT FK_CARRITO FOREIGN KEY (NID_CARRITO)
    REFERENCES TBL_CARRITO(NID_CARRITO),
    CONSTRAINT FK_CARRITO_ARTICULo FOREIGN KEY (NID_ARTICULO)
    REFERENCES TBL_ARTICULOS(NID_ARTICULO)
	)

	INSERT into TBL_USUARIOS(CUSUARIO, CPASSWORD_HASH, CROL, NID_CLIENTE)
	values ('Admin', '202cb962ac59075b964b07152d234b70', 'Admin', null) 
